### ISSUE TITLE
Not a single word about 16 bit string aka WCHAR string.

### ISSUE THREAD

**Issue by kcvinker** [IsaacShelton/AdeptWin32Examples#1]
Windows gui programming means we need to deal with 16 bit wchar string. But there is no single example in this repo with wchar string.

**Comment by IsaacShelton** [comment]
Windows supports UTF-8 via a flag if I remember correctly.

Adept does not support wide char strings, hence why there's not a demo for it

**Comment by kcvinker** [comment]
> Adept does not support wide char strings, hence why there's not a demo for it

No probs, If there is a 16 bit primitive data type, we can create a wchar pointer.

**Comment by IsaacShelton** [comment]
Yes, the wchar_t FuncitonW versions are the same as the FunctionA versions, you'd just have to use something like `*ushort` instead of `*ubyte`.

Keep in mind though that there are no ushort string literals, so you'd have to process your text into wchar_t strings in the code. But otherwise, it should work as you'd expect.
